# Generated by Django 3.0.8 on 2020-08-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menu_menuchild'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(default='', max_length=120, verbose_name='路由'),
        ),
        migrations.AlterField(
            model_name='menuchild',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Menu', verbose_name='上级菜单'),
        ),
    ]
