# Generated by Django 3.0.8 on 2020-08-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200802_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
        migrations.AddField(
            model_name='menuchild',
            name='url',
            field=models.CharField(default='', max_length=120, verbose_name='路由'),
        ),
    ]
