# Generated by Django 3.0.8 on 2020-08-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200802_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='18550774645', max_length=20, verbose_name='手机号'),
        ),
    ]
