# Generated by Django 3.0.8 on 2020-08-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('api', '0006_auto_20200803_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='role',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group', verbose_name='分组列表'),
        ),
    ]
