# Generated by Django 3.0.8 on 2020-08-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200807_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='info',
            field=models.CharField(default='', max_length=600, verbose_name='角色描述'),
        ),
    ]
