# Generated by Django 3.0.8 on 2020-08-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('api', '0008_role_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permlist',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Permission', verbose_name='权限列表'),
        ),
    ]
