# Generated by Django 3.0.8 on 2020-08-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_role_permlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='管理员', max_length=120, unique=True, verbose_name='角色名'),
        ),
    ]
