# Generated by Django 3.0.8 on 2020-08-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('api', '0010_auto_20200808_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsLevelOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='分类名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('level', models.SmallIntegerField(default=1, verbose_name='等级')),
            ],
            options={
                'verbose_name': '一级分类',
                'verbose_name_plural': '一级分类',
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-create_date'], 'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.CreateModel(
            name='RolePermlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.SmallIntegerField(blank=True, null=True, verbose_name='组id')),
                ('permissions', models.ManyToManyField(blank=True, null=True, to='auth.Permission', verbose_name='权限列表')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='GoodsLevelTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='分类名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('level', models.SmallIntegerField(default=2, verbose_name='等级')),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GoodsLevelOne', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '二级分类',
                'verbose_name_plural': '二级分类',
            },
        ),
        migrations.CreateModel(
            name='GoodsLevelThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='分类名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('level', models.SmallIntegerField(default=3, verbose_name='等级')),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GoodsLevelTwo', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '三级分类',
                'verbose_name_plural': '三级分类',
            },
        ),
    ]
