# Generated by Django 3.0.8 on 2020-08-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200811_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodslevelthree',
            name='previous',
        ),
        migrations.RemoveField(
            model_name='goodsleveltwo',
            name='previous',
        ),
        migrations.DeleteModel(
            name='GoodsLevelOne',
        ),
        migrations.DeleteModel(
            name='GoodsLevelThree',
        ),
        migrations.DeleteModel(
            name='GoodsLevelTwo',
        ),
    ]
