# Generated by Django 3.0.8 on 2020-08-16 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200811_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='groups',
        ),
    ]
