# Generated by Django 3.0.8 on 2020-08-11 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsLevelOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='分类名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('level', models.SmallIntegerField(default=1, verbose_name='等级')),
            ],
            options={
                'verbose_name': '一级分类',
                'verbose_name_plural': '一级分类',
            },
        ),
        migrations.CreateModel(
            name='GoodsLevelTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='分类名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('level', models.SmallIntegerField(default=2, verbose_name='等级')),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsLevelOne', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '二级分类',
                'verbose_name_plural': '二级分类',
            },
        ),
        migrations.CreateModel(
            name='GoodsLevelThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='分类名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('level', models.SmallIntegerField(default=3, verbose_name='等级')),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsLevelTwo', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '三级分类',
                'verbose_name_plural': '三级分类',
            },
        ),
    ]
