# Generated by Django 3.0.8 on 2020-08-13 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200811_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodslevelthree',
            name='GoodsLevelTwo',
        ),
        migrations.RemoveField(
            model_name='goodsleveltwo',
            name='GoodsLevelOne',
        ),
        migrations.AddField(
            model_name='goodslevelthree',
            name='father',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goods.GoodsLevelTwo', verbose_name='上级菜单'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsleveltwo',
            name='father',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goods.GoodsLevelOne', verbose_name='上级菜单'),
            preserve_default=False,
        ),
    ]
