# Generated by Django 3.0.8 on 2020-08-14 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goodsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='标签名称')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('goodsInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodsinfo', to='goods.GoodSInfo', verbose_name='分类标签')),
            ],
            options={
                'verbose_name': '参数标签',
                'verbose_name_plural': '参数标签',
                'ordering': ['-create_date'],
            },
        ),
    ]
