# Generated by Django 3.0.8 on 2020-08-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20200816_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=640, unique=True, verbose_name='商品名称')),
                ('goods_price', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='商品价格')),
                ('goods_number', models.IntegerField(default=0, verbose_name='商品数量')),
                ('goods_weight', models.CharField(max_length=120, verbose_name='商品重量')),
                ('goods_state', models.SmallIntegerField(choices=[(0, '未通过'), (1, '审核中'), (2, '已审核')], default=0, verbose_name='商品状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('up_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hot_mumber', models.IntegerField(default=0, verbose_name='热销品数量')),
                ('is_promote', models.BooleanField(default=0, verbose_name='是否是热销品')),
            ],
            options={
                'verbose_name': '参数标签',
                'verbose_name_plural': '参数标签',
                'ordering': ['-up_time'],
            },
        ),
    ]
