# Generated by Django 3.0.8 on 2020-08-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_goodslist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodslist',
            options={'ordering': ['-up_time'], 'verbose_name': '商品列表', 'verbose_name_plural': '商品列表'},
        ),
        migrations.AlterField(
            model_name='goodslist',
            name='goods_price',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='商品价格'),
        ),
    ]
