# Generated by Django 3.0.8 on 2020-08-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20200816_2234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodsList',
            new_name='GoodsProductList',
        ),
    ]
