# Generated by Django 3.0.8 on 2020-08-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20200818_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsimage',
            name='name',
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(upload_to='image/', verbose_name='图片文件'),
        ),
    ]
