# Generated by Django 3.1 on 2020-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20200818_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsproductlist',
            name='goods_animate',
            field=models.JSONField(blank=True, null=True, verbose_name='动态信息'),
        ),
        migrations.AddField(
            model_name='goodsproductlist',
            name='goods_static',
            field=models.JSONField(blank=True, null=True, verbose_name='静态信息'),
        ),
    ]
