# Generated by Django 3.1 on 2020-08-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20200818_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsproductlist',
            name='goods_cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.goodslevelthree', verbose_name='商品分类'),
        ),
    ]
