# Generated by Django 3.1 on 2020-08-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0017_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=120, unique=True, verbose_name='订单编号')),
                ('order_price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='订单价格')),
                ('order_pay', models.BooleanField(default=False, verbose_name='是否付款')),
                ('is_send', models.BooleanField(default=False, verbose_name='是否发货')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('up_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('goods', models.ManyToManyField(blank=True, null=True, to='goods.GoodsProductList', verbose_name='商品列表')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
